name: code_challenger
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_code_editor: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
    - family: Consolas
      fonts:
        - asset: assets/fonts/consolas/CONSOLA.TTF
        - asset: assets/fonts/consolas/consolai.ttf
          style: italic
        - asset: assets/fonts/consolas/CONSOLAB.TTF
          weight: 400
        
